export const NEW_ITEM = 'NEW_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const MORE_ITEM = 'MORE_ITEM'
export const LESS_ITEM = 'LESS_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const FROM_FILE = 'FROM_FILE'
export const SET_USER = 'SET_USER'
